language: node_js
node_js:
  - "8"
script:
 - npm run test-ci
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
sudo: required
dist: trusty
cache:
  directories:
    - "node_modules"
notifications:
  email: false
